/** device_simulator.cpp — IoT设备模拟器 (SRS 附录8) */
#include <iostream>
#include <sstream>
#include <iomanip>
#include <fstream>
#include <thread>
#include <chrono>
#include <atomic>
#include <csignal>
#include <cstring>
#include <random>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <netdb.h>

namespace U {
inline int64_t now(){return std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
inline std::string rhex(int n){static std::mt19937 g(std::random_device{}());std::ostringstream o;o<<std::hex<<std::setfill('0');for(int i=0;i<n;i++)o<<std::setw(2)<<(g()&0xFF);return o.str();}
inline std::string jg(const std::string& j,const std::string& k){auto p=j.find("\""+k+"\":\"");if(p==std::string::npos)return"";p+=k.size()+4;auto e=j.find('"',p);return e!=std::string::npos?j.substr(p,e-p):"";}
}

struct Http {std::string h_;int p_=80;struct R{int s=0;std::string b;};Http(const std::string& u){auto x=u;if(x.find("http://")==0)x=x.substr(7);auto c=x.find(':');h_=c!=std::string::npos?x.substr(0,c):x;p_=c!=std::string::npos?std::stoi(x.substr(c+1)):80;}
R post(const std::string& p,const std::string& b){return req("POST",p,b);}R get(const std::string& p){return req("GET",p,"");}
R req(const std::string& m,const std::string& p,const std::string& b){R r;int fd=socket(AF_INET,SOCK_STREAM,0);if(fd<0)return r;timeval tv{5,0};setsockopt(fd,SOL_SOCKET,SO_RCVTIMEO,&tv,sizeof(tv));setsockopt(fd,SOL_SOCKET,SO_SNDTIMEO,&tv,sizeof(tv));addrinfo h{},*res;h.ai_family=AF_INET;h.ai_socktype=SOCK_STREAM;if(getaddrinfo(h_.c_str(),std::to_string(p_).c_str(),&h,&res)!=0){close(fd);return r;}sockaddr_in a{};memcpy(&a,res->ai_addr,sizeof(a));freeaddrinfo(res);if(connect(fd,(sockaddr*)&a,sizeof(a))<0){close(fd);return r;}std::ostringstream rs;rs<<m<<" "<<p<<" HTTP/1.1\r\nHost: "<<h_<<":"<<p_<<"\r\nContent-Type: application/json\r\nConnection: close\r\n";if(!b.empty())rs<<"Content-Length: "<<b.size()<<"\r\n";rs<<"\r\n"<<b;auto s=rs.str();send(fd,s.c_str(),s.size(),0);char buf[65536];auto n=recv(fd,buf,sizeof(buf)-1,0);close(fd);if(n<=0)return r;buf[n]=0;auto x=std::string(buf);auto st=x.find(' ');if(st!=std::string::npos)r.s=std::stoi(x.substr(st+1,3));auto bs=x.find("\r\n\r\n");if(bs!=std::string::npos)r.b=x.substr(bs+4);return r;}};

struct Mqtt {int fd_=-1;std::string h_,will_t_,will_m_;int p_=1883;std::atomic<bool> ok_{false};uint16_t pid_=1;std::string err_;static std::string el(uint32_t l){std::string r;do{uint8_t b=l&0x7F;l>>=7;if(l)b|=0x80;r+=(char)b;}while(l);return r;}static std::string es(const std::string& s){uint16_t l=htons(s.size());return std::string((char*)&l,2)+s;}bool re(void* b,size_t n){size_t o=0;auto*p=(char*)b;while(o<n){auto r=recv(fd_,p+o,n-o,0);if(r<=0)return false;o+=r;}return true;}bool rp(uint8_t& t,std::string& pl){uint8_t h;if(!re(&h,1))return false;t=h>>4;uint32_t l=0,sh=0;while(1){uint8_t b;if(!re(&b,1))return false;l|=(b&0x7F)<<sh;sh+=7;if(!(b&0x80))break;}pl.resize(l);if(l>0&&!re(&pl[0],l))return false;return true;}
public:void set_will(const std::string& t,const std::string& m){will_t_=t;will_m_=m;}
bool conn(const std::string& uri,const std::string& cid,const std::string& u,const std::string& p){auto s=uri;if(s.find("tcp://")==0)s=s.substr(6);else if(s.find("ssl://")==0||s.find("tls://")==0)s=s.substr(6);else if(s.find("mqtt://")==0)s=s.substr(7);auto c=s.find(':');h_=(c!=std::string::npos)?s.substr(0,c):s;p_=(c!=std::string::npos)?std::stoi(s.substr(c+1)):1883;fd_=socket(AF_INET,SOCK_STREAM,0);if(fd_<0){err_="socket failed";return false;}timeval tv{5,0};setsockopt(fd_,SOL_SOCKET,SO_RCVTIMEO,&tv,sizeof(tv));setsockopt(fd_,SOL_SOCKET,SO_SNDTIMEO,&tv,sizeof(tv));addrinfo h{},*res;h.ai_family=AF_INET;h.ai_socktype=SOCK_STREAM;if(getaddrinfo(h_.c_str(),std::to_string(p_).c_str(),&h,&res)!=0){err_="DNS: "+h_;close(fd_);fd_=-1;return false;}sockaddr_in a{};memcpy(&a,res->ai_addr,sizeof(a));freeaddrinfo(res);if(::connect(fd_,(sockaddr*)&a,sizeof(a))<0){err_="TCP refused";close(fd_);fd_=-1;return false;}bool hasW=!will_t_.empty();uint8_t flg=0x02;if(!u.empty()){flg|=0x80;if(!p.empty())flg|=0x40;}if(hasW){flg|=0x04;flg|=(1<<3);}std::string v;v.push_back(0x00);v.push_back(0x04);v+="MQTT";v.push_back(0x04);v.push_back((char)flg);v.push_back(0x00);v.push_back(0x3C);v+=es(cid);if(hasW){v+=es(will_t_);v+=es(will_m_);}if(!u.empty()){v+=es(u);if(!p.empty())v+=es(p);}std::string pk;pk+=(char)0x10;pk+=el(v.size());pk+=v;send(fd_,pk.c_str(),pk.size(),0);std::string pl;uint8_t tp;if(!rp(tp,pl)){err_="no CONNACK";close(fd_);fd_=-1;return false;}if(tp!=2||pl.size()<2||pl[1]!=0){err_="CONNACK code="+std::to_string(pl.size()>=2?(int)(unsigned char)pl[1]:-1);close(fd_);fd_=-1;return false;}ok_=true;return true;}
std::string error(){return err_;}bool sub(const std::string& t,int q=1){if(!ok_)return false;uint16_t i=htons(pid_++);std::string v;v.append((char*)&i,2);v+=es(t);v+=(char)q;std::string pk;pk+=(char)0x82;pk+=el(v.size());pk+=v;send(fd_,pk.c_str(),pk.size(),0);return true;}bool pub(const std::string& t,const std::string& pl,int q=1){if(!ok_)return false;std::cerr<<"[MQTT] → "<<t<<" | "<<(pl.size()>200?pl.substr(0,200)+"...":pl)<<std::endl;std::string v;v+=es(t);if(q>0){uint16_t i=htons(pid_++);v.append((char*)&i,2);}v+=pl;uint8_t h=(uint8_t)(0x30|(q<<1));std::string pk;pk+=(char)h;pk+=el(v.size());pk+=v;send(fd_,pk.c_str(),pk.size(),0);return true;}void disc(){ok_=false;if(fd_>=0){char d[]={(char)0xE0,0x00};send(fd_,d,2,0);close(fd_);fd_=-1;}}bool ok(){return ok_;}};

struct Sim {struct Cfg{std::string url="http://127.0.0.1:9080",mqtt_uri="tcp://127.0.0.1:1883",hwuid,mk="01KXW0CFN798QFGS86XBDG574A";int hb=30,dur=0;bool no_mqtt=false;};Cfg cfg;Http http_;Mqtt mqtt_;std::atomic<bool> run_{true};std::string did_,tid_,pid_,tok_,bri_,mc_,fw_,tname_;int stat_=0;bool ev_done[3]={};
Sim(const Cfg& c):cfg(c),http_(c.url){if(cfg.hwuid.empty())cfg.hwuid="SIM-"+U::rhex(8);}~Sim(){if(mqtt_.ok()&&!did_.empty())mqtt_.pub(did_+"/v1/status","{\"status\":\"offline\"}");mqtt_.disc();}void L(const std::string& m){std::cerr<<"[Sim] "<<m<<std::endl;}

void resolve_tenant(){auto kr=http_.get("/api/v1/mqtt-tenant-key");std::string key=U::jg(kr.b,"tenant_key");if(!key.empty()&&key!="null"){auto vr=http_.get("/api/v1/mqtt-tenant-key/verify?key="+key);std::string nm=U::jg(vr.b,"tenant_name");if(!nm.empty()){tname_=nm;L("  MQTT租户: "+tname_+" (接口)");save();return;}}if(!tname_.empty())L("  MQTT租户: "+tname_+" (缓存)");}

bool activate(){L("══════ 阶段1: HTTP设备激活 ══════");std::ostringstream b;b<<"{\"uid\":\""<<cfg.hwuid<<"\",\"model_key\":\""<<cfg.mk<<"\"}";L("→ POST /api/v1/device/activate");auto r=http_.post("/api/v1/device/activate",b.str());if(r.s!=201&&r.s!=200){L("✗ 激活失败: "+r.b.substr(0,200));if(!did_.empty()){L("⚠ 使用本地凭证");return true;}return false;}did_=U::jg(r.b,"device_id");tid_=U::jg(r.b,"tenant_id");pid_=U::jg(r.b,"product_id");tok_=U::jg(r.b,"activation_token");bri_=U::jg(r.b,"mqtt_broker_uri");mc_=U::jg(r.b,"model_code");fw_=U::jg(r.b,"firmware_version");if(bri_.empty()||bri_.find("example.com")!=std::string::npos)bri_=cfg.mqtt_uri;L("✓ 激活成功 device="+did_+" model="+mc_+" fw="+fw_);resolve_tenant();save();return true;}

bool load(){std::ifstream f("./device_creds.json");if(!f.is_open())return false;std::string j((std::istreambuf_iterator<char>(f)),std::istreambuf_iterator<char>());did_=U::jg(j,"device_id");tid_=U::jg(j,"tenant_id");pid_=U::jg(j,"product_id");tok_=U::jg(j,"token");bri_=U::jg(j,"broker_uri");mc_=U::jg(j,"model_code");fw_=U::jg(j,"firmware_version");tname_=U::jg(j,"mqtt_tenant");if(did_.empty())return false;L("✓ 已激活(缓存) device="+did_+" model="+mc_);resolve_tenant();return true;}

void save(){std::ofstream f("./device_creds.json");f<<"{\"device_id\":\""<<did_<<"\",\"tenant_id\":\""<<tid_<<"\",\"product_id\":\""<<pid_<<"\",\"token\":\""<<tok_<<"\",\"broker_uri\":\""<<bri_<<"\",\"model_code\":\""<<mc_<<"\",\"firmware_version\":\""<<fw_<<"\",\"mqtt_tenant\":\""<<tname_<<"\"}";}

bool connect_mqtt(){if(cfg.no_mqtt){L("⚠ MQTT skipped");return true;}std::string base=did_+"/v1";std::string mqtt_user=(tname_.empty()?tid_:tname_);L("══════ 阶段2: MQTT连接 ══════");L("  broker: "+bri_);L("  clientId: "+did_);L("  username: "+mqtt_user);mqtt_.set_will(base+"/status","{\"status\":\"offline\"}");if(!mqtt_.conn(bri_,did_,mqtt_user,"")){L("✗ MQTT失败: "+mqtt_.error());return false;}mqtt_.sub(base+"/property/set");mqtt_.sub(base+"/ota/notify");mqtt_.sub(base+"/command/+");mqtt_.pub(base+"/status","{\"status\":\"online\"}",1);L("✓ MQTT已连接");return true;}

void run(){L("══════ 阶段3: 运行 (心跳"+std::to_string(cfg.hb)+"s) ══════");auto st=std::chrono::steady_clock::now();int cy=0;while(run_){cy++;auto e=std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now()-st).count();L("── 周期 "+std::to_string(cy)+" (t+"+std::to_string(e)+"s) ──");heartbeat();if(cy%3==0)properties();if(cy==4){stat_=1;ev("order_completed","{\"order_id\":\"ORD-"+U::rhex(4)+"\",\"recipe_id\":\"REC-AMERICANO-001\",\"recipe_name\":\"经典美式\",\"cup_size\":\"中\",\"ts\":"+std::to_string(U::now())+"}");L("[Event] 订单完成");stat_=0;}if(cy==8){stat_=2;ev("fault_alert","{\"fault_code\":3,\"level\":\"error\",\"description\":\"水泵流量异常(模拟)\",\"ts\":"+std::to_string(U::now())+"}");L("[Event] 错误 E003");}if(cy==12){stat_=0;ev("fault_resolved","{\"fault_code\":3,\"level\":\"error\",\"ts\":"+std::to_string(U::now())+"}");L("[Event] 恢复 E003");}if(cfg.dur>0&&e>=cfg.dur){run_=false;break;}for(int i=0;i<cfg.hb&&run_;i++){std::this_thread::sleep_for(std::chrono::seconds(1));auto e2=std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now()-st).count();if(e2>=3&&!ev_done[0]){ev_done[0]=true;stat_=1;ev("order_completed","{\"order_id\":\"ORD-"+U::rhex(4)+"\",\"recipe_id\":\"REC-AMERICANO-001\",\"recipe_name\":\"经典美式\",\"cup_size\":\"中\",\"ts\":"+std::to_string(U::now())+"}");L("[Event] 订单完成");stat_=0;heartbeat();}if(e2>=6&&!ev_done[1]){ev_done[1]=true;stat_=2;ev("fault_alert","{\"fault_code\":3,\"level\":\"error\",\"description\":\"水泵流量异常(模拟)\",\"ts\":"+std::to_string(U::now())+"}");L("[Event] 错误 E003");heartbeat();}if(cfg.dur>0&&e2>=cfg.dur){run_=false;break;}if(e2>=9&&!ev_done[2]){ev_done[2]=true;stat_=0;ev("fault_resolved","{\"fault_code\":3,\"level\":\"error\",\"ts\":"+std::to_string(U::now())+"}");L("[Event] 恢复 E003");heartbeat();}}}}
void stop(){run_=false;}
void heartbeat(){std::ostringstream b;b<<"{\"device_id\":\""<<did_<<"\",\"ts\":"<<U::now()<<",\"network_status\":0,\"work_status\":"<<stat_<<",\"fw_ver\":\""<<fw_<<"\"}";if(mqtt_.ok())mqtt_.pub(did_+"/v1/heartbeat",b.str());else{auto r=http_.post("/api/v1/device/heartbeat",b.str());L("[HTTP] heartbeat → "+std::to_string(r.s));}}
void properties(){std::ostringstream b;b<<"{\"cpu_temp_c\":"<<(45+rand()%20)<<",\"water_temp_c\":"<<(85+rand()%10)<<"}";if(mqtt_.ok())mqtt_.pub(did_+"/v1/property/post",b.str());}
void ev(const std::string& t,const std::string& d){std::string b="{\"event_type\":\""+t+"\","+d.substr(1);if(mqtt_.ok())mqtt_.pub(did_+"/v1/event/post",b);}
};

static Sim* gs=nullptr;void sh(int){(void)0;if(gs)gs->stop();}
int main(int argc,char* argv[]){std::cerr<<std::unitbuf;signal(SIGINT,sh);signal(SIGTERM,sh);Sim::Cfg cfg;for(int i=1;i<argc;i++){std::string a=argv[i];if(a=="--url"&&i+1<argc)cfg.url=argv[++i];else if(a=="--mqtt"&&i+1<argc)cfg.mqtt_uri=argv[++i];else if(a=="--model-key"&&i+1<argc)cfg.mk=argv[++i];else if(a=="--interval"&&i+1<argc)cfg.hb=std::stoi(argv[++i]);else if(a=="--duration"&&i+1<argc)cfg.dur=std::stoi(argv[++i]);else if(a=="--hw-uid"&&i+1<argc)cfg.hwuid=argv[++i];else if(a=="--skip-mqtt")cfg.no_mqtt=true;else if(a=="--reactivate"){std::remove("./device_creds.json");std::cerr<<"[Sim] 凭证已清除"<<std::endl;}else if(a=="--help"){std::cerr<<R"(Usage: device_simulator [OPTIONS]
  --url URL      云端地址 (default: http://127.0.0.1:9080)
  --mqtt URI     MQTT Broker (default: tcp://127.0.0.1:1883)
  --model-key KEY  型号Key (26-char ULID)
  --interval SEC   心跳间隔 (default: 30)
  --duration SEC   运行时长 0=永久
  --skip-mqtt      纯HTTP模式
  --reactivate     清除凭证
)";return 0;}}std::cerr<<"\n═══ IoT Device Simulator v3.0 ═══\n  URL: "<<cfg.url<<"  MQTT: "<<cfg.mqtt_uri<<"  model_key: "<<cfg.mk<<"\n"<<std::endl;Sim sim(cfg);gs=&sim;if(!sim.load()){if(!sim.activate()){std::cerr<<"[FATAL] 激活失败, 云端是否运行?\n";return 1;}}sim.connect_mqtt();sim.run();std::cerr<<"\n[Sim] 结束\n";return 0;}
